services:
  alexraskin-dev:
    image: ghcr.io/alexraskin/alexraskin.com:${GIT_COMMIT_HASH:-latest}
    networks:
      - traefik-public
    labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.web-https.rule=Host(`alexraskin.dev`) || Host(`www.alexraskin.dev`)"
        - "traefik.http.routers.web-https.entrypoints=https"
        - "traefik.http.routers.web-https.tls=true"
        - "traefik.http.routers.web-https.tls.certresolver=le"
        - "traefik.http.routers.web-https.middlewares=non-www-to-www"
        - "traefik.http.middlewares.non-www-to-www.redirectregex.regex=^https?://alexraskin\\.dev(.*)"
        - "traefik.http.middlewares.non-www-to-www.redirectregex.replacement=https://www.alexraskin.dev$${1}"
        - "traefik.http.middlewares.non-www-to-www.redirectregex.permanent=true"
        - "traefik.http.services.web-https.loadbalancer.server.port=8000"
    deploy:
      update_config:
        order: start-first

networks:
  traefik-public:
    external: true