services:
  alexraskin-com:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alexraskin-com
    ports:
      - "8000:8000"
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - README.md
            - docker-compose.base.yml
            - docker-stack.yml
